ansible-collections/community.elastic

plugins/modules/elastic_bulk.py

A few documentation improvements.
- Docs Pull Request
elastic_bulk

Documentation improvements

---

plugins/modules/elastic_index.py
plugins/modules/elastic_index_info.py
tests/integration/targets/elastic_index_info/meta/main.yml
tests/integration/targets/elastic_index_info/tasks/1-test-no-auth.yml
tests/integration/targets/elastic_index_info/tasks/2-test-with-auth.yml
tests/integration/targets/elastic_index_info/tasks/main.yml

Refactor code into elastic_index_info module as the sanity tests insist.
elastic_index_info

Refactor index info functionality into its own module

---

.github/workflows/ansible-test.yml

See if sanity tests correctly run against all Python versions. 

Run sanity tests on all Python versions

---

.github/workflows/ansible-test.yml
plugins/modules/elastic_bulk.py

Trying Python2.7 in the CI.
ansible-test.yml

Try python2.7 in CI

---

plugins/modules/elastic_rollup.py
plugins/modules/elastic_transform.py
tests/integration/targets/elastic_bulk/tasks/1-test-no-auth.yml
tests/integration/targets/elastic_bulk/tasks/2-test-with-auth.yml
tests/integration/targets/elastic_rollup/tasks/1-test-no-auth.yml
tests/integration/targets/elastic_transform/meta/main.yml
tests/integration/targets/elastic_transform/tasks/1-test-no-auth.yml
tests/integration/targets/elastic_transform/tasks/main.yml

Adds elastic_transform module
elastic_transform

Initial commit of elastic_transform module

---

plugins/modules/elastic_pipeline.py
plugins/modules/elastic_transform.py
tests/integration/targets/elastic_pipeline/meta/main.yml
tests/integration/targets/elastic_pipeline/tasks/1-test-no-auth.yml
tests/integration/targets/elastic_pipeline/tasks/main.yml

Initial commit of module.
elastic_pipeline

Inital commit of module

---

.github/workflows/ansible-test.yml

Add ansible 2.11 to matrix
ansible-test.yml

Add ansible-2.11 to matrix

---

plugins/modules/elastic_index.py
plugins/modules/elastic_index_lifecycle.py
tests/integration/targets/elastic_index_lifecycle/meta/main.yml
tests/integration/targets/elastic_index_lifecycle/tasks/1-test-no-auth.yml
tests/integration/targets/elastic_index_lifecycle/tasks/2-test-with-auth.yml
tests/integration/targets/elastic_index_lifecycle/tasks/main.yml

Initial commit of module and tests.
elastic_index_lifecycle

Initial commit of module and tests

---

plugins/modules/elastic_bulk.py

Set supports_check_mode 0 False
elastic_bulk

elastic_bulk

---

plugins/modules/elastic_index.py
tests/integration/targets/elastic_index/tasks/1-test-no-auth.yml
tests/integration/targets/elastic_index/tasks/2-test-with-auth.yml

Adds check mode support for present and absent states.
elastic_index

Add check_mode support and tests

---

plugins/modules/elastic_pipeline.py
tests/integration/targets/elastic_pipeline/tasks/1-test-no-auth.yml

Try to fix yaml tests. Problems escaping complex pipeline.
elastic_pipeline

Try to fix yaml tests

---

plugins/modules/elastic_snapshot_repository.py
tests/integration/targets/elastic_snapshot_repository/meta/main.yml
tests/integration/targets/elastic_snapshot_repository/tasks/1-test-no-auth.yml
tests/integration/targets/elastic_snapshot_repository/tasks/2-test-with-auth.yml
tests/integration/targets/elastic_snapshot_repository/tasks/main.yml
tests/integration/targets/setup_elastic/docker/3-node-with-kibana-no-auth.yml
tests/integration/targets/setup_elastic/docker/single-node-elastic-with-auth.yml
tests/integration/targets/setup_elastic/docker/single-node-elastic.yml

Adds elastic_snapshot_repository module and tests.
elastic_snapshot_repository

elastic_snapshot_repository: Add module and tests

---

plugins/modules/elastic_snapshot.py
tests/integration/targets/elastic_snapshot/meta/main.yml
tests/integration/targets/elastic_snapshot/tasks/1-test-no-auth.yml
tests/integration/targets/elastic_snapshot/tasks/2-test-with-auth.yml
tests/integration/targets/elastic_snapshot/tasks/main.yml

Initial commit of module and tests.
elastic_snapshot

elastic_snapshot: Initial commit of module and tests

---

tests/integration/targets/setup_elastic/tasks/main.yml

Add pip install of docker module.
setup_elastic

Add pip install of docker module

---

README.md
plugins/module_utils/elastic_common.py

Implements https://github.com/ansible-collections/community.elastic/issues/53
elastic_common.py

Add fallback to options

---

.github/workflows/ansible-test.yml
README.md
plugins/doc_fragments/login_options.py
plugins/module_utils/elastic_common.py
plugins/modules/elastic_index.py

Removes master_timeout that's no longer present in driver.

Remove master_timeout

---

README.md
plugins/doc_fragments/login_options.py
plugins/module_utils/elastic_common.py

Reverts ansible-collections/community.elastic#54

Revert "Add fallback to options"

---

plugins/doc_fragments/login_options.py
plugins/modules/elastic_index.py
plugins/modules/elastic_index_lifecycle.py
plugins/modules/elastic_user.py

Reported by sanity checks... https://github.com/ansible-collections/community.elastic/actions/runs/3374780838/jobs/5601535342
- Docs Pull Request

Documentation updates

---

plugins/module_utils/elastic_common.py
plugins/modules/elastic_bulk.py
plugins/modules/elastic_reindex.py
plugins/modules/elastic_snapshot.py
plugins/modules/elastic_snapshot_repository.py

Remove/ignore "unused" imports. Common file contains a number of imports that are then imported from a module. These are ignored.

Sanity checks

---

plugins/doc_fragments/login_options.py
plugins/module_utils/elastic_common.py

Update module choices to confirm with sanity
- Sanity fix
elastic_common.py

Update module choices to confirm with sanity

---

changelogs/changelog.yaml
galaxy.yml
meta/runtime.yml

Stuff for 1.0.0 release

---

.github/workflows/ansible-test.yml
.github/workflows/publish_collection.yml

Updates workflows to remove depreciated functions
Workflows

Updates workflows to remove depreciated functions

---

.github/workflows/ansible-test.yml
.github/workflows/publish_collection.yml

Increment Python to 3.10

---

changelogs/changelog.yaml
galaxy.yml

Stuff for 1.1.0 release
- Release

Stuff for 1.1.0 release

---

.github/workflows/ansible-test.yml
.github/workflows/publish_collection.yml

Upgrade a few actions in the CI.

Upgrade a few actions

---

changelogs/changelog.yaml
galaxy.yml

Stuff for 1.1.2 release
- Release

Stuff for 1.1.2 release

---

changelogs/changelog.yaml
galaxy.yml

Stuff for 1.1.3 release
- Release

Stuff for 1.1.3 release

---

changelogs/changelog.yaml
galaxy.yml

Stuff for 1.2.0 release.
- Release

Stuff for 1.2.0 release

---

tests/integration/targets/setup_elastic/tasks/main.yml

Fixes issue in CI.
https://github.com/ansible-collections/community.elastic/actions/runs/13044812217/job/36396865892
apt update required.

Updates package name

---

changelogs/changelog.yaml
galaxy.yml

Stuff for 1.2.1 release
- Release

Stuff for 1.2.1 release

---

changelogs/changelog.yaml
galaxy.yml

Stuff for 1.2.2 release
- Release
community.elastic

Stuff for 1.2.2 release

---

.github/workflows/ansible-test.yml
.github/workflows/publish_collection.yml
tests/integration/targets/elastic_cluster_health/tasks/2-test-3-node-with-kibana-no-auth.yml
tests/integration/targets/elastic_cluster_health/tasks/4-test-3-node-with-kibana-with-auth.yml
tests/integration/targets/elastic_cluster_settings/tasks/2-test-3-node-with-kibana-no-auth.yml
tests/integration/targets/elastic_cluster_settings/tasks/4-test-3-node-with-kibana-with-auth.yml
tests/integration/targets/elastic_rollup/tasks/1-test-no-auth.yml
tests/integration/targets/setup_elastic/handlers/main.yml
tests/integration/targets/setup_elastic/tasks/main.yml
tests/integration/targets/setup_local_elastic/handlers/main.yml

Bump Ubuntu runner
